### ISSUE TITLE
Possible error with other Timezone formats?

### ISSUE THREAD

**Issue by lululujojo123** [labnex/LabNex#39]
**I confirm that I have searched the issue tracker**
Before opening an issue, take a few minutes to search the issue tracker (both open and closed issues) for the problem you are facing. This will reduce the need for issue triage and save time.

 - [x] I confirm that I have searched the issue tracker

**Describe the bug**
Crashing on every single view wen trying to load anything. PR, Repos oder other functions in the home menu.

**To Reproduce**
Using a self hosted instance with German Timezone settings

**Expected behavior**
The menu should appear instead of a parse exception

**Logs**
2024-12-31 01:50:26.796 19117 19117 com.labnex.app E AndroidRuntime : FATAL EXCEPTION: main
Process: com.labnex.app, PID: 19117
j$.time.format.DateTimeParseException: Text '2024-07-11T17:00:55.468+02:00' could not be parsed at index 23
	at j$.time.format.DateTimeFormatter.parseResolved0(SourceFile:1999)
	at j$.time.format.DateTimeFormatter.parse(SourceFile:1901)
	at j$.time.Instant.parse(SourceFile:395)
	at com.labnex.app.adapters.MergeRequestsAdapter$MergeRequestsHolder.bindData(MergeRequestsAdapter.java:220)
	at com.labnex.app.adapters.MergeRequestsAdapter.onBindViewHolder(MergeRequestsAdapter.java:71)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7747)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7847)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6646)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6917)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6757)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6753)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4645)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4348)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4919)
	at android.view.View.layout(View.java:23265)
	at android.view.ViewGroup.layout(ViewGroup.java:6415)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:689)
	at android.view.View.layout(View.java:23265)
	at android.view.ViewGroup.layout(ViewGroup.java:6415)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23265)
	at android.view.ViewGroup.layout(ViewGroup.java:6415)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
	at com.google.android.material.appbar.ViewOffsetBehavior.layoutChild(ViewOffsetBehavior.java:66)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:153)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2365)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
	at android.view.View.layout(View.java:23265)
	at android.view.ViewGroup.layout(ViewGroup.java:6415)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23265)
	at android.view.ViewGroup.layout(ViewGroup.java:6415)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23265)
	at android.view.ViewGroup.layout(ViewGroup.java:6415)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23265)
	at android.view.ViewGroup.layout(ViewGroup.java:6415)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)

**Screenshots**
Not really as App crashes.

**Versions (please complete the following information)**
 - LabNex: 2.0.0
 - Android: 12
 - GitLab: n/a

**GitLab instance**
 - [ ] gitlab.com
 - [ ] framagit.org
 - [x] Self-hosted instance
 - [ ] Other service (Name/URL: )

**Mode of installation**
 - [ ] Google Play Store
 - [x] F-droid
 - [ ] APK
 - [ ] Built from source
 - [ ] OpenAPK
 - [ ] Other stores (Name: )

**Additional context**
Crash appears in every menu at every button in home view.

**Comment by lululujojo123** [comment]
Opened a Pull Request with a possible solution in my view. But didn't test it in much constellations.
